### ISSUE TITLE
Markdown support?

### ISSUE THREAD

**Issue by Layarion** [Athari/CsConsoleFormat#25]
I'm new to programming, dunno if there are good tools for this out there but most things I'm finding has all this HTML stuff that I don't want to learn or fuss with.

Instead of .Yellow(), can I just use markdown instead?

**Comment by Athari** [comment]
@Layarion 
Standard Windows console doesn't support formatting which Markdown provides, like font variations, underlines etc. And I believe no console on any OS supports links and such. So while Markdown can be kinda supported on *nix to produce escape codes, it won't be cross-platform even within *nix world as terminal formatting capabilities and escape codes vary.

Markdown is primarily designed to produce HTML; HTML is primarily designed to not be restricted by native console formatting. So just like with any other complex text formatting (be it HTML, DOCX, TEX or anything else), it isn't fit for console as it's technically impossible to produce the output that this formatting expects withing the restrictions of the terminal. "Previewing" of complex formatting within console is possible, but using it as the main method of output within your app would be frustrating, wasteful and slow.
