### ISSUE TITLE
Text Color not working on Linux

### ISSUE THREAD

**Issue by DkAngelito** [Athari/CsConsoleFormat#26]
Hi,
Is it possible to display colors for text on Linux (RHEL)? 

I formatted some documents with colored text on Windows and everything works fine

![CipheConsoleWIn](https://user-images.githubusercontent.com/10522969/85162794-8ac73080-b227-11ea-9076-33774e7c105b.jpg)
This is how it looks on Windows

but when I run it on Linux (Redhat Enterprise Linux) no colors are displayed as you can see in the following picture.
![CipheConsoleRHEL](https://user-images.githubusercontent.com/10522969/85162913-b21dfd80-b227-11ea-92d0-7004bf2a7f6e.jpg)

To note, the system is able to show colors, as seen in the above picture, with the ls command files and directories are listed using colors.

So why it does not show correctly the colors? Do I have to do something special?

**Comment by Athari** [comment]
@DkAngelito 
The library is using standard .NET API for terminal (`Console.ForegroundColor` and `Console.BackgroundColor`), so if you're using the default console rendering, then it works if and only if the standard .NET API works.

System API for console colors differs massively on Windows and *nix. In case of Windows, it's ancient API which works the same way on every Windows (plus I assume new API for newest Windows 10 console; haven't checked it out yet). In case of Linux, it's non-standartized ANSI codes which differ from one *nix to another, from one terminal to another. .NET performs some dark magic to detect what's supposed to work and I assume when it fails, it doesn't provide color support.

If that is the case, you can still get colored output using this library, but you'll have to manually provide ANSI codes for `AnsiRenderTarget` and pass it to the rendering function.
