### ISSUE TITLE
Dotnet Core?

### ISSUE THREAD

**Issue by Chiliyago** [Athari/CsConsoleFormat#29]
Will this library compile well with dotnet core? Is there a newer dotnet core version of this library?  Thanks for your attention

**Comment by Athari** [comment]
The library includes fully functional .NET Standard 1.3 and 2.0 builds, which means it's compatible with .NET Core 1.0+. You can find the list of compatible frameworks in the ReadMe: https://github.com/Athari/CsConsoleFormat/blob/master/ReadMe.md#framework-compatibility.

Also even libraries built for old .NET Framework versions are mostly compatible with .NET Core for quite some time, so in general you shouldn't worry about compatibility of libraries which don't rely on platform-dependent features like WinForms or GDI+.
